version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
  product-service:
    build: ./product-service
    ports:
      - "8080:8080"
  order-service:
    build: ./order-service
    ports:
      - "8002:8002"
  payment-service:
    build: ./payment-service
    ports:
      - "8081:8081"
  notification-service:
    build: ./notification-service
    ports:
      - "3002:3002"